package plugin

import (
	"fmt"
	"path"
	"path/filepath"
	"runtime"

	"github.com/dave/jennifer/jen"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/compiler/protogen"
)

const nexusPkg = "github.com/nexus-rpc/sdk-go/nexus"
const workflowPkg = "go.temporal.io/sdk/workflow"

const generatedFilenameExtension = "_nexus_temporal.pb.go"
const generatedPackageSuffix = "nexustemporal"
const generatedNexusPackageSuffix = "nexus"

var multiLineValues = jen.Options{
	Close:     "}",
	Multi:     true,
	Open:      "{",
	Separator: ",",
}

type Options struct {
	lang string
}

type Plugin struct {
	*protogen.Plugin
	version string
	commit  string
	options Options
	flags   *pflag.FlagSet
}

func New(version, commit string) *Plugin {
	flags := pflag.NewFlagSet("plugin", pflag.ExitOnError)
	p := &Plugin{
		version: version,
		commit:  commit,
		flags:   flags,
	}
	flags.StringVar(&p.options.lang, "lang", "", "language output to render (go)")

	return p
}

func (p *Plugin) Param(key, value string) error {
	return p.flags.Set(key, value)
}

func (p *Plugin) Run(plugin *protogen.Plugin) error {
	if p.options.lang != "go" {
		return fmt.Errorf("provided -lang flag is not supported: %q", p.options.lang)
	}
	p.Plugin = plugin
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}

		nexusPkgName := path.Join(
			string(file.GoImportPath),
			string(file.GoPackageName+generatedNexusPackageSuffix),
		)
		file.GoPackageName += generatedPackageSuffix
		prefixToSlash := filepath.ToSlash(file.GeneratedFilenamePrefix)
		file.GeneratedFilenamePrefix = path.Join(
			path.Dir(prefixToSlash),
			string(file.GoPackageName),
			path.Base(prefixToSlash),
		)
		importPath := path.Join(
			string(file.GoImportPath),
			string(file.GoPackageName),
		)

		f := jen.NewFilePathName(importPath, string(file.GoPackageName))

		p.genCodeGenerationHeader(f, file)

		var hasContent bool
		for _, svc := range file.Services {
			hasContent = true
			p.genClient(f, svc, nexusPkgName)
		}

		if !hasContent {
			continue
		}

		if err := f.Render(
			p.Plugin.NewGeneratedFile(
				file.GeneratedFilenamePrefix+generatedFilenameExtension,
				protogen.GoImportPath(importPath),
			),
		); err != nil {
			return fmt.Errorf("error rendering file: %w", err)
		}
	}

	return nil
}

func (p *Plugin) genCodeGenerationHeader(f *jen.File, target *protogen.File) {
	f.PackageComment("Code generated by protoc-gen-nexus-temporal. DO NOT EDIT.")
	f.PackageComment("versions: ")
	f.PackageComment(fmt.Sprintf("    protoc-gen-nexus-temporal %s (%s)", p.version, p.commit))
	f.PackageComment(fmt.Sprintf("    go %s", runtime.Version()))
	compilerVersion := p.Plugin.Request.CompilerVersion
	if compilerVersion != nil {
		f.PackageComment(fmt.Sprintf("    protoc %s", compilerVersion.String()))
	} else {
		f.PackageComment("    protoc (unknown)")
	}

	f.PackageComment(fmt.Sprintf("source: %s", target.Desc.Path()))
}

func methodIO(method *protogen.Method) (*jen.Statement, *jen.Statement) {
	var input *jen.Statement
	if method.Input.Desc.FullName() != "google.protobuf.Empty" {
		input = jen.Op("*").Qual(string(method.Input.GoIdent.GoImportPath), method.Input.GoIdent.GoName)
	} else {
		input = jen.Qual(nexusPkg, "NoValue")
	}

	var output *jen.Statement
	if method.Output.Desc.FullName() != "google.protobuf.Empty" {
		output = jen.Op("*").Qual(string(method.Output.GoIdent.GoImportPath), method.Output.GoIdent.GoName)
	} else {
		output = jen.Qual(nexusPkg, "NoValue")
	}
	return input, output
}

func (p *Plugin) genClient(f *jen.File, svc *protogen.Service, nexusPkgPath string) {
	structName := fmt.Sprintf("%sNexusClient", svc.GoName)

	f.Type().
		Id(structName).
		StructFunc(func(g *jen.Group) {
			g.Id("client").Qual(workflowPkg, "NexusClient")
		})

	ctorName := fmt.Sprintf("New%sNexusClient", svc.GoName)
	f.Commentf("%s initializes a new %s.", ctorName, structName)
	f.Func().
		Id(ctorName).
		ParamsFunc(func(g *jen.Group) {
			g.Id("endpoint").String()
		}).
		Op("*").Id(structName).
		BlockFunc(func(g *jen.Group) {
			g.ReturnFunc(func(g *jen.Group) {
				g.Op("&").Id(structName).CustomFunc(multiLineValues, func(g *jen.Group) {
					g.Id("client").Op(":").Qual(workflowPkg, "NewNexusClient").CallFunc(func(g *jen.Group) {
						g.Id("endpoint")
						g.Qual(nexusPkgPath, fmt.Sprintf("%sServiceName", svc.GoName))
					})
				})
			})
		})

	for _, method := range svc.Methods {
		syncMethodName := method.GoName
		asyncMethodName := fmt.Sprintf("%sAsync", method.GoName)
		futureName := fmt.Sprintf("%sFuture", method.GoName)
		input, output := methodIO(method)

		hasInput := method.Input.Desc.FullName() != "google.protobuf.Empty"
		hasOutput := method.Output.Desc.FullName() != "google.protobuf.Empty"
		if !hasOutput {
			futureName = "workflow.NexusOperationFuture"
		}

		if hasOutput {
			f.Type().Id(futureName).StructFunc(func(g *jen.Group) {
				g.Qual(workflowPkg, "NexusOperationFuture")
			})

			f.Func().
				ParamsFunc(func(g *jen.Group) {
					g.Id("f").Op("*").Id(futureName)
				}).
				Id("GetTyped").
				ParamsFunc(func(g *jen.Group) {
					g.Id("ctx").Qual(workflowPkg, "Context")
				}).
				Params(output, jen.Error()).
				BlockFunc(func(g *jen.Group) {
					g.Var().Id("output").Qual(string(method.Output.GoIdent.GoImportPath), method.Output.GoIdent.GoName)

					g.Id("err").Op(":=").Id("f").Dot("Get").CallFunc(func(g *jen.Group) {
						g.Id("ctx")
						g.Op("&").Id("output")
					})
					g.Return().Op("&").Id("output").Op(",").Id("err")
				})
		}

		f.Func().
			ParamsFunc(func(g *jen.Group) {
				g.Id("c").Op("*").Id(structName)
			}).
			Id(asyncMethodName).
			ParamsFunc(func(g *jen.Group) {
				g.Id("ctx").Qual(workflowPkg, "Context")
				if hasInput {
					g.Id("input").Add(input)
				}
				g.Id("options").Qual(workflowPkg, "NexusOperationOptions")
			}).
			Id(futureName).
			BlockFunc(func(g *jen.Group) {
				g.Id("fut").Op(":=").Id("c").Dot("client").Dot("ExecuteOperation").
					CallFunc(func(g *jen.Group) {
						g.Id("ctx")
						g.Qual(nexusPkgPath, operationNameConst(svc, method))
						if hasInput {
							g.Id("input")
						} else {
							g.Nil()
						}
						g.Id("options")
					})
				if hasOutput {
					g.Return().Id(futureName).BlockFunc(func(g *jen.Group) {
						g.Id("fut").Op(",")
					})
				} else {
					g.Return().Id("fut")
				}
			})

		f.Func().
			ParamsFunc(func(g *jen.Group) {
				g.Id("c").Op("*").Id(structName)
			}).
			Id(syncMethodName).
			ParamsFunc(func(g *jen.Group) {
				g.Id("ctx").Qual(workflowPkg, "Context")
				if hasInput {
					g.Id("input").Add(input)
				}
				g.Id("options").Qual(workflowPkg, "NexusOperationOptions")
			}).
			ParamsFunc(func(g *jen.Group) {
				if hasOutput {
					g.Add(output)
				}
				g.Error()
			}).
			BlockFunc(func(g *jen.Group) {
				if hasOutput {
					g.Var().Id("output").Qual(string(method.Output.GoIdent.GoImportPath), method.Output.GoIdent.GoName)
				}

				g.Id("fut").Op(":=").Id("c").Dot("client").Dot("ExecuteOperation").
					CallFunc(func(g *jen.Group) {
						g.Id("ctx")
						g.Qual(nexusPkgPath, operationNameConst(svc, method))
						if hasInput {
							g.Id("input")
						} else {
							g.Nil()
						}
						g.Id("options")
					})
				if hasOutput {
					g.Id("err").Op(":=").Id("fut").Dot("Get").CallFunc(func(g *jen.Group) {
						g.Id("ctx")
						g.Op("&").Id("output")
					})
					g.Return().Op("&").Id("output").Op(",").Id("err")
				} else {
					g.Id("err").Op(":=").Id("fut").Dot("Get").CallFunc(func(g *jen.Group) {
						g.Id("ctx")
						g.Nil()
					})
					g.Return().Id("err")
				}
			})
	}
}

func operationNameConst(svc *protogen.Service, method *protogen.Method) string {
	return fmt.Sprintf("%s%sOperationName", svc.GoName, method.GoName)
}
